version: "3.9"

services:
  database:
    image: 'postgres:latest'
    container_name: postgres_ecommerce
    ports:
      - '5434:5432'
    environment:
      - 'POSTGRES_USER=maysara'
      - 'POSTGRES_DB=maysara'
      - 'POSTGRES_PASSWORD=maysara'
    volumes:
      - ecommerce_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maysara"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_ecommerce
    ports:
      - '5050:80'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@admin.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - ecommerce_network

volumes:
  ecommerce_postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  ecommerce_network:
    driver: bridge
